-- Création des utilisateurs
CREATE USER devUser WITH PASSWORD 'pass123';
CREATE USER testUser WITH PASSWORD 'testPass';
CREATE USER prodUser WITH PASSWORD 'secureProdPass';

-- Création des bases de données
CREATE DATABASE DEV_DATABASE OWNER devUser;
CREATE DATABASE TEST_DATABASE OWNER testUser;
CREATE DATABASE PROD_DATABASE OWNER prodUser;

-- Attribution des privilèges
GRANT ALL PRIVILEGES ON DATABASE DEV_DATABASE TO devUser;
GRANT ALL PRIVILEGES ON DATABASE TEST_DATABASE TO testUser;
GRANT ALL PRIVILEGES ON DATABASE PROD_DATABASE TO prodUser;